/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AngelCoavas.Examenes.version.Front_end.vistas;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author HP5
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MenuLaboratorio = new javax.swing.JLabel();
        MenuAdMin = new javax.swing.JLabel();
        MenuCertificadoDeCalidad = new javax.swing.JLabel();
        MenuSubir = new javax.swing.JLabel();
        MenuRequisitos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        TablaDeLab = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EXAMENES CLINICOS");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        MenuLaboratorio.setBackground(new java.awt.Color(74, 74, 207));
        MenuLaboratorio.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        MenuLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        MenuLaboratorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/matraz.png"))); // NOI18N
        MenuLaboratorio.setText("LABORATORIO");
        MenuLaboratorio.setOpaque(true);
        MenuLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLaboratorioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuLaboratorioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuLaboratorioMouseExited(evt);
            }
        });

        MenuAdMin.setBackground(new java.awt.Color(74, 74, 207));
        MenuAdMin.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        MenuAdMin.setForeground(new java.awt.Color(255, 255, 255));
        MenuAdMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/admin (2).png"))); // NOI18N
        MenuAdMin.setText("ADMIN");
        MenuAdMin.setOpaque(true);
        MenuAdMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdMinMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuAdMinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuAdMinMouseExited(evt);
            }
        });

        MenuCertificadoDeCalidad.setBackground(new java.awt.Color(74, 74, 207));
        MenuCertificadoDeCalidad.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        MenuCertificadoDeCalidad.setForeground(new java.awt.Color(255, 255, 255));
        MenuCertificadoDeCalidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/certificado.png"))); // NOI18N
        MenuCertificadoDeCalidad.setText("CDC");
        MenuCertificadoDeCalidad.setOpaque(true);
        MenuCertificadoDeCalidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuCertificadoDeCalidadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuCertificadoDeCalidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuCertificadoDeCalidadMouseExited(evt);
            }
        });

        MenuSubir.setBackground(new java.awt.Color(74, 74, 207));
        MenuSubir.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        MenuSubir.setForeground(new java.awt.Color(255, 255, 255));
        MenuSubir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/subir (1).png"))); // NOI18N
        MenuSubir.setText("SUBIR");
        MenuSubir.setOpaque(true);
        MenuSubir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSubirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuSubirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuSubirMouseExited(evt);
            }
        });

        MenuRequisitos.setBackground(new java.awt.Color(74, 74, 207));
        MenuRequisitos.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        MenuRequisitos.setForeground(new java.awt.Color(255, 255, 255));
        MenuRequisitos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/listas-de-verificacion.png"))); // NOI18N
        MenuRequisitos.setText("REQUISITOS");
        MenuRequisitos.setOpaque(true);
        MenuRequisitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuRequisitosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuRequisitosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MenuRequisitosMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clinica (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuAdMin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuCertificadoDeCalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuSubir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuRequisitos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MenuLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(MenuAdMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(MenuCertificadoDeCalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MenuSubir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(MenuRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setForeground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(626, 532));

        jLabel4.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 224));
        jLabel4.setText("CREADORES:\n\nSERGIO VEGA \n\nANGEL COAVAS\n \nJUAN DIEGO BARRAZA\n ©");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addContainerGap(498, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        TablaDeLab.setBackground(new java.awt.Color(102, 102, 255));
        TablaDeLab.setForeground(new java.awt.Color(0, 0, 153));
        TablaDeLab.setText("Usuarios de Laboratorio");
        TablaDeLab.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        TablaDeLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDeLabMouseClicked(evt);
            }
        });
        TablaDeLab.add(jSeparator1);

        jMenuBar1.add(TablaDeLab);

        jMenu2.setBackground(new java.awt.Color(102, 102, 255));
        jMenu2.setForeground(new java.awt.Color(0, 0, 153));
        jMenu2.setText("Usuarios de Admin");
        jMenu2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.add(jSeparator2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaboratorioMouseClicked
        Panel_1 p1 = new Panel_1();
        p1.setSize(626, 532);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_MenuLaboratorioMouseClicked

    private void MenuAdMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdMinMouseClicked
       Panel_2 p2 = new Panel_2();
        p2.setSize(626, 532);
        p2.setLocation(0,0);
        
        content.removeAll();
        content.add(p2, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
        
    }//GEN-LAST:event_MenuAdMinMouseClicked

    private void MenuCertificadoDeCalidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCertificadoDeCalidadMouseClicked
        Panel_3 p3 = new Panel_3();
        p3.setSize(626, 532);
        p3.setLocation(0,0);
        
        content.removeAll();
        content.add(p3, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MenuCertificadoDeCalidadMouseClicked

    private void MenuSubirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSubirMouseClicked
        Panel_4 p4 = new Panel_4();
        p4.setSize(626, 532);
        p4.setLocation(0,0);
        
        content.removeAll();
        content.add(p4, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MenuSubirMouseClicked

    private void MenuRequisitosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRequisitosMouseClicked
        Panel_5 p5 = new Panel_5();
        p5.setSize(626, 532);
        p5.setLocation(0,0);
        
        content.removeAll();
        content.add(p5, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_MenuRequisitosMouseClicked

    private void MenuLaboratorioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaboratorioMouseEntered
         MenuLaboratorio.setBackground(new Color(255,255,255));
         MenuLaboratorio.setForeground(Color.BLUE);
         
        
    }//GEN-LAST:event_MenuLaboratorioMouseEntered

    private void MenuLaboratorioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLaboratorioMouseExited
         MenuLaboratorio.setBackground(new Color(74,74,207));
         MenuLaboratorio.setForeground(Color.white);
    }//GEN-LAST:event_MenuLaboratorioMouseExited

    private void MenuAdMinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdMinMouseEntered
          MenuAdMin.setBackground(new Color(255,255,255));
         MenuAdMin.setForeground(Color.BLUE);
       
    }//GEN-LAST:event_MenuAdMinMouseEntered

    private void MenuAdMinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdMinMouseExited
         MenuAdMin.setBackground(new Color(74,74,207));
         MenuAdMin.setForeground(Color.white);
    }//GEN-LAST:event_MenuAdMinMouseExited

    private void MenuCertificadoDeCalidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCertificadoDeCalidadMouseEntered
        MenuCertificadoDeCalidad.setBackground(new Color(255,255,255));
         MenuCertificadoDeCalidad.setForeground(Color.BLUE);
         
         
    }//GEN-LAST:event_MenuCertificadoDeCalidadMouseEntered

    private void MenuCertificadoDeCalidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuCertificadoDeCalidadMouseExited
         MenuCertificadoDeCalidad.setBackground(new Color(74,74,207));
         MenuCertificadoDeCalidad.setForeground(Color.white);
    }//GEN-LAST:event_MenuCertificadoDeCalidadMouseExited

    private void MenuSubirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSubirMouseEntered
        MenuSubir.setBackground(new Color(255,255,255));
         MenuSubir.setForeground(Color.BLUE);
         
       
    }//GEN-LAST:event_MenuSubirMouseEntered

    private void MenuSubirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSubirMouseExited
         MenuSubir.setBackground(new Color(74,74,207));
         MenuSubir.setForeground(Color.white);
    }//GEN-LAST:event_MenuSubirMouseExited

    private void MenuRequisitosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRequisitosMouseEntered
         MenuRequisitos.setBackground(new Color(255,255,255));
         MenuRequisitos.setForeground(Color.BLUE);
        
    }//GEN-LAST:event_MenuRequisitosMouseEntered

    private void MenuRequisitosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuRequisitosMouseExited
        MenuRequisitos.setBackground(new Color(74,74,207));
         MenuRequisitos.setForeground(Color.white);
    }//GEN-LAST:event_MenuRequisitosMouseExited

    private void TablaDeLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDeLabMouseClicked
        ListaDeEnsayos tablaDeLab = new ListaDeEnsayos(this, true);
        tablaDeLab.setVisible(true);
    }//GEN-LAST:event_TablaDeLabMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        ListaDeAdmin tableAdmin = new ListaDeAdmin(this, true);
        tableAdmin.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuAdMin;
    private javax.swing.JLabel MenuCertificadoDeCalidad;
    private javax.swing.JLabel MenuLaboratorio;
    private javax.swing.JLabel MenuRequisitos;
    private javax.swing.JLabel MenuSubir;
    private javax.swing.JMenu TablaDeLab;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
