/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AngelCoavas.Examenes.version.Front_end.vistas;
 

import AngelCoavas.Examenes.version.controllers.AdminJpaController;
import AngelCoavas.Examenes.version.models.Admin;
import AngelCoavas.Examenes.version.models.Laboratiorio;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author HP5
 */
public class Panel_2 extends javax.swing.JPanel {

    /**
     * Creates new form Panel_2
     */
    Integer idEncontrado;
    public Panel_2() {
        initComponents();
        TextPrompt txt1 = new TextPrompt("Ingresa su nombre y apellido", txtNombreApellido);
        TextPrompt txt2 = new TextPrompt("Ingresa el id de usuario", txtBuscar);
        
        txt1.setForeground(Color.GRAY);
        txt2.setForeground(Color.GRAY);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        txtNombreApellido = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        txtCalendar = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        btnBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(626, 532));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 91));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 224));
        jLabel2.setText("Nombre y apellido:");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 224));
        jLabel3.setText("Codigo:");

        jLabel4.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 224));
        jLabel4.setText("Fecha de Ensayo:");

        jLabel5.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 224));
        jLabel5.setText("Contenido");

        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 224));
        btnAgregar.setText("Agregar");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 224));
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        btnBuscar.setBackground(new java.awt.Color(0, 0, 224));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(0, 0, 224));
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(txtCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCod))
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 153, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnAgregar)
                .addGap(60, 60, 60)
                .addComponent(btnEliminar)
                .addGap(52, 52, 52)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCod)
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar)
                        .addComponent(btnEliminar)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
          if (!txtNombreApellido.getText().equals("")
                && !txtCod.getText().equals("")
                && !txtContenido.getText().equals("")) {

            //Definir EntityManagerFactory
            EntityManagerFactory emf = new Persistence().createEntityManagerFactory("Examenes_clinicosPU");
            //Definir la instancia del controlador
              AdminJpaController controller = new AdminJpaController(emf);

            //Obtener los valores de todos los campos
            String NombreApellido = txtNombreApellido.getText();
            String Contenido = txtContenido.getText();
            
           

            //Instanciar una universidad y darle todos los valores segun los obtenidos arriba
            Admin ad = new Admin();
            ad.setNombre(NombreApellido);
            ad.setContenido(Contenido);
            ad.setFechaCertificado(txtCalendar.getLinkDay());
            //Definir un try catch
            try {
                //Accedemos al metodo crear del controlador y le pasamos la universidad creada arriba
                controller.create(ad);
                //Si sale bien mostramos
                JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO");
            } catch (Exception e) {
                //Si sale mal mostramos
                JOptionPane.showMessageDialog(null, "Hubo error, intentelo nuevamente");
            }
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
          if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba un id para buscar");
        } else {
            EntityManagerFactory emf = new Persistence().createEntityManagerFactory("Examenes_clinicosPU");
            AdminJpaController controller = new AdminJpaController(emf);

            Integer id = Integer.parseInt(txtBuscar.getText());
            try {
                controller.destroy(id);
                JOptionPane.showMessageDialog(null, "Uusuario Eliminado ");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Hubo un error, intente nuevamente");
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
         if (txtBuscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Escriba un id para buscar");
        } else {
            //Definir EntityManagerFactory
            EntityManagerFactory emf = new Persistence().createEntityManagerFactory("Examenes_clinicosPU");
            //Definir la instancia del controlador
            AdminJpaController controller = new AdminJpaController(emf);

            //obtener el id del campo de texto
            Integer id = Integer.parseInt(txtBuscar.getText());

            try {
                //Una variable 
                Admin AdminEncontrado = controller.findAdmin(id);
                idEncontrado = AdminEncontrado.getIdAdmin();

                txtNombreApellido.setText(AdminEncontrado.getNombre());
                txtContenido.setText(AdminEncontrado.getContenido());
                txtBuscar.setText(String.valueOf(AdminEncontrado.getIdAdmin()));
                JOptionPane.showMessageDialog(null, "Encontrada");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se encontro");
            }

        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(Color.GRAY);
        btnAgregar.setForeground(Color.red);
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
         btnAgregar.setBackground(new Color(255,255,255));
        btnAgregar.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(Color.GRAY);
        btnEliminar.setForeground(Color.red);
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        btnEliminar.setBackground(new Color(255,255,255));
        btnEliminar.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
          btnBuscar.setBackground(Color.GRAY);
        btnBuscar.setForeground(Color.red);
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
       btnBuscar.setBackground(new Color(255,255,255));
        btnBuscar.setForeground(Color.BLUE);
    }//GEN-LAST:event_btnBuscarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    private org.jdesktop.swingx.JXDatePicker txtCalendar;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextField txtNombreApellido;
    // End of variables declaration//GEN-END:variables
}
