/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package AngelCoavas.Examenes.version.Front_end.vistas;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.JobAttributes;
import java.io.FileOutputStream;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import javax.swing.JOptionPane;


/**
 *
 * @author HP5
 */
public class Panel_3 extends javax.swing.JPanel {

    /**
     * Creates new form Panel_3
     */
    public Panel_3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.OD
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGenerarCertificado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreDeAdmin = new javax.swing.JTextField();
        txtCodigoDevalidez = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenidoDeCertificado = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(290, 91));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CERTIFICADO DE CALIDAD ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        btnGenerarCertificado.setBackground(new java.awt.Color(255, 255, 255));
        btnGenerarCertificado.setFont(new java.awt.Font("Consolas", 1, 24)); // NOI18N
        btnGenerarCertificado.setForeground(new java.awt.Color(0, 0, 224));
        btnGenerarCertificado.setText("GENERAR CERTIFICADO");
        btnGenerarCertificado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCertificadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 224));
        jLabel2.setText("Nombre De Jefe:");

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 224));
        jLabel3.setText("Codigo de validez:");
        jLabel3.setToolTipText("");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CONTENIDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Franklin Gothic Medium", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        txtContenidoDeCertificado.setColumns(20);
        txtContenidoDeCertificado.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        txtContenidoDeCertificado.setRows(5);
        jScrollPane1.setViewportView(txtContenidoDeCertificado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(btnGenerarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoDevalidez, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreDeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreDeAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                        .addGap(0, 0, 0)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCodigoDevalidez, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerarCertificado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarCertificadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCertificadoActionPerformed
        String NombreDeAdmin = txtNombreDeAdmin.getText();
       String CodigoDeValidez = txtCodigoDevalidez.getText();
       String ContenidoDeEnsayo = txtContenidoDeCertificado.getText();     
        Document docs = new Document();
        
       Paragraph title = new Paragraph("EXAMENES CLINICOS");
       
       
        try {
            String rut = System.getProperty("user.home");
            PdfWriter.getInstance(docs, new FileOutputStream(rut + "/Desktop/Historia Clinica.pdf"));
            docs.open();
            docs.add(title);
            title.setAlignment(Element.ALIGN_CENTER);
            
            docs.add(new Paragraph("Nombre de jefe: " + NombreDeAdmin));
            docs.add(new Paragraph("Codigo de validez: " + CodigoDeValidez));
            docs.add(new Paragraph("Fecha de certficado: " + LocalDateTime.now()));
            
            docs.add(Chunk.NEWLINE);
            Paragraph body = new Paragraph(ContenidoDeEnsayo);
            
            body.setAlignment(Element.ALIGN_JUSTIFIED);
            docs.add(body);
            
            docs.add(Chunk.NEWLINE);
            
            docs.add(new Paragraph("__________________________________"));
            docs.add(new Paragraph("FIRMA DE JEFE DE CLINICA"));
            
            docs.add(new Paragraph("__________________________________"));
            docs.add(new  Paragraph("FIRMA DE CLIENTE "));
            
            docs.close();
            JOptionPane.showMessageDialog(null, "SU CERTIFICADO FUE CREADO DE MANERA EXITOSA");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
             
      
    }//GEN-LAST:event_btnGenerarCertificadoActionPerformed
 

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarCertificado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCodigoDevalidez;
    private javax.swing.JTextArea txtContenidoDeCertificado;
    private javax.swing.JTextField txtNombreDeAdmin;
    // End of variables declaration//GEN-END:variables

    
}
